# ======================================
# AegisGuard v1.0 - Config
# ======================================

# ======================================
# Global Settings
# ======================================
messages:
  language_style: "old_english"  # Options: old_english / modern
  allow_runtime_switch: true     # If true, allows live style switching via GUI/admin command

# ======================================
# Economy (Global Defaults)
# ======================================
use_vault: true
claim_cost: 100.0
item_cost:
  type: DIAMOND
  amount: 5
refund_on_unclaim: false
refund_percent: 0

# ======================================
# Claims & Limits
# ======================================
claims:
  max_claims_per_player: 1
  min_radius: 1
  max_radius: 32
  max_area: 16000
  preview_seconds: 10

  per_world:
    world:
      use_vault: true
      vault_cost: 200.0
      item_cost:
        type: EMERALD
        amount: 10
      refund_on_unclaim: true
      refund_percent: 50
      max_claims_per_player: 2
      min_radius: 4
      max_radius: 48
      max_area: 25000
      protections:
        pvp_protection: true
        no_mobs_in_claims: true
        container_protection: true
        pets_protection: true
        entities_protection: true
        farm_protection: true

    world_nether:
      use_vault: false
      item_cost:
        type: GOLD_INGOT
        amount: 20
      refund_on_unclaim: false
      refund_percent: 0
      max_claims_per_player: 1
      min_radius: 2
      max_radius: 16
      max_area: 8000
      protections:
        pvp_protection: false
        no_mobs_in_claims: false
        container_protection: true
        pets_protection: false
        entities_protection: true
        farm_protection: false

    world_the_end:
      max_claims_per_player: 0
      protections:
        pvp_protection: true
        no_mobs_in_claims: true
        container_protection: false
        pets_protection: false
        entities_protection: true
        farm_protection: false

# ======================================
# Sounds
# ======================================
sounds:
  global_enabled: true
  players: {}

# ======================================
# Protections
# ======================================
protections:
  pvp_protection: true
  container_protection: true
  pets_protection: true
  entities_protection: true
  farm_protection: true

# ======================================
# Admin Options
# ======================================
admin:
  auto_remove_banned: false
  bypass_claim_limit: false
  broadcast_admin_actions: false
