# ======================================
# AegisGuard v1.0 - Config
# ======================================
# Quick Defaults
# ======================================
use_vault: true            # true = use Vault currency, false = item cost
claim_cost: 100.0          # Vault cost per claim (only if use_vault = true)

item_cost:                 # Item payment alternative (only if use_vault = false)
  type: DIAMOND
  amount: 5

refund_on_unclaim: false   # true = give players refunds when unclaiming
refund_percent: 0          # % refunded (0 = none, 50 = half, 100 = full)

# ======================================
# Claiming & Limits
# ======================================
limits:
  min_radius: 1             # Minimum radius for a claim (in blocks)
  max_radius: 32            # Maximum radius for a claim (in blocks)
  max_area: 16000           # Maximum total claim area (blocks^2)
  preview_seconds: 10       # How long (in seconds) a claim preview lasts

# ======================================
# Effects & Visuals
# ======================================
effects:
  on_claim:
    lightning_visual: true   # Strike lightning effect when a claim is made
    particle: TOTEM          # Particle effect when claiming (TOTEM, FLAME, HEART, etc.)

# ======================================
# Protections
# ======================================
protections:
  no_mobs_in_claims: true      # Prevent hostile mobs from spawning inside claims
  pvp_protection: true         # Disable PvP inside claims (trusted players exempt)
  container_protection: true   # Block non-trusted players from opening chests/furnaces

# ======================================
# Sounds & Immersion
# ======================================
sounds:
  global_enabled: true         # Master toggle:
                               # - true: Sounds are enabled globally by default
                               # - false: Disables ALL sounds plugin-wide (players cannot re-enable)
  players: {}                  # Per-player toggles stored automatically

# ======================================
# Admin Options
# ======================================
admin:
  auto_remove_banned: false       # Remove all plots of a banned player automatically
  bypass_claim_limit: false       # Allow admins to bypass claim limits
  broadcast_admin_actions: false  # If true, admin actions are shown to ALL players
                                  # If false (default), only admins + console see them
