# ======================================
# AegisGuard v1.0 - Config
# ======================================

# ======================================
# Economy
# ======================================
use_vault: true            # true = use Vault currency, false = item cost
claim_cost: 100.0          # Vault cost per claim (only if use_vault = true)

item_cost:                 # Item payment alternative (only if use_vault = false)
  type: DIAMOND
  amount: 5

refund_on_unclaim: false   # true = give players refunds when unclaiming
refund_percent: 0          # % refunded (0 = none, 50 = half, 100 = full)

# ======================================
# Claims & Limits
# ======================================
claims:
  max_claims_per_player: 1  # Maximum number of claims a player can own
  min_radius: 1             # Minimum radius for a claim (in blocks)
  max_radius: 32            # Maximum radius for a claim (in blocks)
  max_area: 16000           # Maximum total claim area (blocks^2)
  preview_seconds: 10       # How long (in seconds) a claim preview lasts

# ======================================
# Effects & Visuals
# ======================================
effects:
  on_claim:
    lightning_visual: true   # Strike lightning effect when a claim is made
    particle: TOTEM          # Particle effect when claiming (TOTEM, FLAME, HEART, etc.)

# ======================================
# Protection Feedback Effects
# ======================================
protection_effects:
  enabled: true               # Master toggle for protection feedback
  defaults:                   # Fallbacks if a protection type is missing
    deny_sound: BLOCK_NOTE_BLOCK_BASS
    deny_particle: SMOKE_NORMAL
    success_sound: ENTITY_EXPERIENCE_ORB_PICKUP
    success_particle: VILLAGER_HAPPY
    fail_sound: BLOCK_ANVIL_LAND
    fail_particle: SMOKE_NORMAL

  # Specific protections (optional overrides)
  pvp:
    deny_sound: ENTITY_ENDERMAN_TELEPORT
    deny_particle: REDSTONE
  containers:
    deny_sound: BLOCK_CHEST_LOCKED
    deny_particle: CRIT
  mobs:
    deny_sound: ENTITY_ZOMBIE_ATTACK_IRON_DOOR
    deny_particle: FLAME
  pets:
    deny_sound: ENTITY_CAT_HISS
    deny_particle: HEART
  entities:
    deny_sound: BLOCK_ANVIL_PLACE
    deny_particle: CRIT_MAGIC
  farm:
    deny_sound: BLOCK_CROP_BREAK
    deny_particle: VILLAGER_ANGRY

# ======================================
# Protections
# ======================================
protections:
  no_mobs_in_claims: true      # Prevent hostile mobs from spawning inside claims
  pvp_protection: true         # Disable PvP inside claims (trusted players exempt)
  container_protection: true   # Block non-trusted players from opening chests/furnaces

# ======================================
# Sounds & Immersion
# ======================================
sounds:
  global_enabled: true         # Master toggle:
                               # - true: Sounds are enabled globally by default
                               # - false: Disables ALL sounds plugin-wide (players cannot re-enable)
  players: {}                  # Per-player toggles stored automatically

# ======================================
# Admin Options
# ======================================
admin:
  auto_remove_banned: false       # Remove all plots of a banned player automatically
  bypass_claim_limit: false       # Allow admins to bypass claim limits
  broadcast_admin_actions: false  # If true, admin actions are shown to ALL players
                                  # If false (default), only admins + console see them
