name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Build
        run: mvn -B -DskipTests package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AegisGuard
          path: target/AegisGuard-*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: AegisGuard
          path: dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.jar"
          generateReleaseNotes: true
